language: cpp

sudo: required
dist: trusty

matrix:
  include:
  - compiler: gcc
  - compiler: clang

before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y
      build-essential
      cmake
      fonts-droid
      libsdl2-dev
      libboost-system-dev
      libboost-filesystem-dev
      libboost-date-time-dev
      libboost-locale-dev
      libfreeimage-dev
      libfreetype6-dev
      libeigen3-dev
      libcurl4-openssl-dev
      libasound2-dev
      libgl1-mesa-dev
  - $CXX --version
  - cmake --version

script:
  - mkdir build && cd build
  - cmake ..
  - make
